### ISSUE TITLE
Fix Readme `pip install` Instruction

### ISSUE THREAD

**Issue by PeiyuanQi** [USCSolarCarStrategyTeam/plotly-dashboard#2]
Change `pip install` to `pip install -r requirements.txt` in **InstallInstallation & Requirements** Part in README.md

**Comment by dkstm95** [comment]
Hi! Can I fix it?

**Comment by PeiyuanQi** [comment]
@dkstm95 
> Hi! Can I fix it?

Yes, please go ahead.
